### ISSUE TITLE
session.setAttribute("User", profile);

### ISSUE THREAD

**Issue by vitalii-kaplan** [nik-vitaly/tp_java#4]
В результате выполнения этого кода в сессии по ключу "User" будет лежать последний созданный профиль. Если вы хотите хранить профиль не в карте у себя, а в сессии, то нужно в качестве ключа использовать идентификатор пользователя. Уникальный для каждого пользователя.
Например User1, User2...
где числа это id профилей.

**Comment by VitalyNikonorov** [comment]
Отменено преподавателем.
