### ISSUE TITLE
class xpathAdapter

### ISSUE THREAD

**Issue by vitalii-kaplan** [nik-vitaly/tp_java#9]
DocumentBuilderFactory factory = DocumentBuilderFactory.newInstance();
            DocumentBuilder builder = factory.newDocumentBuilder();
            Document doc = builder.parse(new File(name));
            XPathFactory xPathfactory = XPathFactory.newInstance();
            XPath xpath = xPathfactory.newXPath();
            XPathExpression expr = xpath.compile(request);
            return expr.evaluate(doc).toString();

Что делает этот код? Создает DOM и обращается к его ноде, заданной переменной request с помощью XPath.

Это решение альтернативное к использованию SAX парсера из моего примера. Я не против такого решения.
Но, задача решена не полностью. Ваша задача написать метод, который на вход возьмет путь к файлу, а на выход отдаст объект ресурса записанного в этом файле.
Ваше решение не собирает ресурс, а обращается к его полям.

Разберите мой пример и заметите в нем использование  SAX на  DocumentBuilder и XPath. Результат должен быть один и тот же -- объект ресурса класс которого указан в тэге <class ..>

**Comment by VitalyNikonorov** [comment]
сделал стандартно. XPath применил в других случаях.
